// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupnmAayTUjgiO8N4kHmAWzrK8uG1f67g',
    appId: '1:373156469186:web:c2b9d294368a8a6518de5b',
    messagingSenderId: '373156469186',
    projectId: 'fir-flutter-codelab-4ff71',
    authDomain: 'fir-flutter-codelab-4ff71.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-4ff71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfV151Std5Uw8xqnPwt0z6jf4iY-9M_uQ',
    appId: '1:373156469186:ios:4d93606910b15f3718de5b',
    messagingSenderId: '373156469186',
    projectId: 'fir-flutter-codelab-4ff71',
    storageBucket: 'fir-flutter-codelab-4ff71.appspot.com',
    iosBundleId: 'com.example.firebaseAuthFlutterfireUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfV151Std5Uw8xqnPwt0z6jf4iY-9M_uQ',
    appId: '1:373156469186:ios:4d93606910b15f3718de5b',
    messagingSenderId: '373156469186',
    projectId: 'fir-flutter-codelab-4ff71',
    storageBucket: 'fir-flutter-codelab-4ff71.appspot.com',
    iosBundleId: 'com.example.firebaseAuthFlutterfireUi',
  );

}